# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire','~>5.0.0-beta.6'
pod 'Kingfisher','~>5.0'

  # Pods for SportsApp

  target 'SportsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
